---
apiVersion: v1
kind: Secret
metadata:
  name: pkcs12-keystore-password
stringData:
  password-key: <KEYSTORE_PASSWORD> # 1Password

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-secret-prod
  annotations:
    issue-temporary-certificate: "true"
spec:
  secretName: solr-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  commonName: "*.solr.iatistandard.org"
  dnsNames:
    - "solr.iatistandard.org"
    - "*.solr.iatistandard.org"
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        key: password-key
        name: pkcs12-keystore-password
  subject:
    countries:
      - UK
    organizationalUnits:
      - k8s
