apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pkcs12-keystore-password
  namespace: default
spec:
  encryptedData:
    password-key: AgCU5f7Kz5eKtXDRTU51FBQGapDBE9rPaN6gloToweDHoRUGZ/n0yWIgIM00IP8o/HLvf/lNj72bYhceFXZ+uWTWtMvD64mR0bTs94cOWgObuFChKybwk66Jb7LIZW4V2Fp8xcGH4+/AvAN3+COozM/qHTN/ECOp57tshmmFmCdWzewtIb+ZWlVtmKHGe4YaJtz+K4pG+HPef2KRUI/Bro6nFAYgacD3UXKCiAH/fKqJvRGEdf/V7mXWWEQUQS7fV2DCnjyVq44BytjKYxZBsMWH4zpgQom7QjsSPU9vwFdfvQ1xAM3g1a5uuS770qr95HtRadVgvd55BWZyePF0NWssJZoPHa4d+k6fDiAJYaXGlXMkXo0qzBwB4KR7OYNIHMyaObYG9Bcl2MnMfkAmZ6MkCK6NdlADmDtMJO62ol0hTmg8FGHEw3R0CUC7Ke/iz8eY9HtvvdDaUFps3RZk/l6ns4JNX7ydUCBBtMkXfmaeg6KA8tbKJHmwaQMbGoyEcbgUgu3vHdMpogHTb2z2Bq/nfEIAzq9qClO00ypgNQR9/f1OBe90WYZvoHGThrRZccWUwP2EaapzBijj7kUOvZzUN325Dgf+OLelJTwQaeysboQXkPl7WS/xDLqEBkeCROGKptR/8uR6m9lHilh5x5aDpygLq8VKp7lSO9FkW1p4TfH3hUlQMTVpJJCEnHe+y4rLAyjYgCeSgOSC5LurnEMqMlN3oY8Bqvg=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: pkcs12-keystore-password
      namespace: default

