apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: solr-get-nodes
  namespace: default
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: solr-get-nodes
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: solr-get-nodes
subjects:
- kind: ServiceAccount
  name: default
  namespace: default