apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: default
spec:
  encryptedData:
    api-token: AgAZHIcIZDCnvdkJKwo4jxswLGUuFQt+OXnlQIpZwwN/ScUWWFrqFu7WsCBVsh7iyaxSVMwYcVdiTLXjhX4c65E6b93gOUUjnpbGs74QQPkwIbcQa387NxBQURGUnoSQrby6VKASAdqoB8HtQcGpSSsk5D+eZPAnriGeUsrmHOZjpjtJmqTRFK2TxaYEn+J1LjhV0p3sXhMjjMihTRbpoPH1x9NUK/alZqIU8KHYgHGsj0fu1nQjpi8Yf/TYY2kBExVZSpM0pF55mhCtqaGl41wlLBNd2Cc+PWrlzewEGBRe4QJ+OEyYHu56JoBHRBxwxpycDZE1dpEiWc26bsbCaDAFjrL5MCPXbf90RhpUUogvuSZK5uZTmN8wUpW5nWpYf8PEtJc0AsS2SXsZvLS2i2CmnGvIKksw5Rt6OO3oZ7j3hr5fG5zm/QW6dhsjLhjnhpyrpuN7v+Tjz7jGBWYWZDf86IKp1WfltmFwBuv/55HR4RRNOszaA2dxjsUmfZw3kTRofBNo4Ug/LQB7IIuUvxcR3o7nF4lFOIHCKlod5HCrkkE4QpnnpBNq5AGrbTzgpO7XwaUzc7bUhmVYCIVXtM7tv6k+XEGJGhw3c9X57nSetCZb57Ud5icwsHsLbqm8+dK5fZ/HmniC/6OArn/z8D3qKNzZjdJJJYpIXeABuN6KwANarPuIsqzIrfKEtgQUYGuW0BaCEk6kMgDmf54IgUvSkrtAmCUv3VdThomW3yi2mVRwpDgnTSsb
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: default
    type: Opaque

