apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: default
spec:
  encryptedData:
    api-token: AgCzSYYET3avf3eqOUvmhDlOGNlS/PXKPe0OctQ5d9xyDONQFqjyJZHT05v/8Ks6jx9mukzqwAXmgtTi5ENJ76us8IfnCx24/BV9OxUvIWUbJOB33Q/6wp0yr02NEYVFzh/Xw6dboa+SaOyiW2FUc3Ryf4GYaSiu5MXNqfz9vxdqqVn8V4MlmEMC0A5d6fC6Kvr/7wnJmwHc9KGHw/NcpfDquenRItTubnL53OCxOD4YEEhyX3QQbHMfYV1G+5C5YJwyyFAFqX6gDShCg29X0TzqpO0YtSvWCakyKfSq5aR2EKzv6Qt1LA46GFzNPGCEX2oExB6tcCgM1gtHzh2JEmSFxh5vjp5Wq+nmFWcu7D9knnGH+yWtnBad3WA1yIze6tlckWyNQ9QRX6eCN7EqfbhKUdnfpb96H/LTM3PzzcLwD0DWyzVmN8Hrd0YVsGYpFgXXzdB9PKD33j6iJnjUXXiszx+FIfFTqM7ZDNGXX53LiOFRtd4Nqw+sxob662+U1/PzJggzxiJ89zwMafH+npPeKN5u/VIabd3XvKTR21R1zDAaVoKnXv2mv53nHjq0U6nXg80PSYnubsFuCA22uacjhQpHnPAUpfnFROthwC/ranvrvbSjKa9p4fmMpu3yEwjM5cDCIAPOBpA6n+yqtRS+1jyKtB1jnpNhcnqZD6U955KivhH03DhbL/GRfXolgkLGZyHVL4sGeKCF/Ci3WegoMkGfVfOGTAm4dUx2Zm1dz9kds9/ImwIU
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: default
    type: Opaque

