apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: default
spec:
  encryptedData:
    api-token: AgA+8EIYrzN0yRusLGd/vWz+OyI+8IGsjYyOPDi7LOH7KDTM5R3XPzoC5fe7HUKBo2JifRmO3CJk7Zb68ofV0TtJfGhOlFs+4SjeB8IUxxAtxRnYMbUzWIj2TLf+bZDdWO3YFtEyeMO2nYIp3mPOQ17767jub9MTQa10Sp2PBbFy447u5oJ7Nd2soahuGJBXUAdvaWhNDkfAlCOwC6FiYQq7rSNhXpd6JDjLEWB4YNiMwhbjhAhzC+vrUykrXJxDI/rdI3t/2nHVr0WgNKgYkPwNRDxNouFdEgXEr1lMoWDOXkGY+t/8oVxCqRvvTLQcKXx1eC3In+lX6kScOfEyUJYUZylUBFzoX0U4OZdjw+CvQ+IJ8LbFnk0qc57pjBa6dK68kF4wjTx2AH4v0HonxOkhDbwUbfljubN/W/gkYDz+uP9HhgaQwT90LrdUEw1J9DeCiQFeMEf+UNsdwEVE7IwZIMWWKaMlkMlQyC08WbG/FckPEIFKqAjzynrO8sPhdbt+3J9JV+tFTfG5k0XFM7gQixmpANEqXlGlZD3RET0Ys1XLDlfj4nY/dumuK82n85exKgO4V+m+tRqtHCl2Kay6LrvcM3Mng0ZxY3SQPGvBF/Eef1HeVLl3QUVYlUKBH3HYqt+OWpkYzEWOx/lJIybhuvrwPrw9MmIGr8bAdYBUzDbaZ/MRfjYkiUn1L46e5EcGAYAdpqsLiAGEbh+QkWFK91CbD0qjGMutS+ksHWUzKV0oQVnF1nQO
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: default
    type: Opaque

