apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pkcs12-keystore-password-dev
  namespace: default
spec:
  encryptedData:
    password-key: AgBCDRmZ3QShjG1WbwJPd1qF+YNSQ9JnbjcR8FLA3Dntqhi2uTsdEdqrNwxmLhjTDpJbfMZM3tEShRTr8H1/KNu1xDeZ2zmDR2+iGcdIXUvh6f8nuAhkXH5rhbUJCaZz5UcTQ8QJgxN5UQHdMdFz4Yo8Eay/XIY1wXIoj2YJbUeMF5Fr/ZNWQ8SJvc0qOsu4V7wqcyq/pQAmF/9BT+F4MWGZ3/CY7Y/uJMIuRh/RxWnqFDCJQFZ4HjuYnPPE/7powjxn1zS/qux7FCZ/TeLSBqpEdxCiUR2LUcVAJorw67rSrJXTvZAmxWjzwxOAPpA+q9xbVBLcaziWg/VVC/1yh3U1mzdcidUIenEzEk+dnoDfAivSIZCZm6zjELbduUL67CJKnAAhGLEUuVglWVELXpEKlN+M0QY0VwOUvM6jk3jT4KLKMsQae+V5AIrqgdW7RESyWX9Z/bTE1ZL7SZKUVBdfPpEzt21duviQ5Ls1wMWx/ZK1o/oDTQkFmBvjdJMHEfx9vosLlMgPUYETGTzYY0wqJFTHWgomSAWhpFgeP42nm9PNYsDmsEHuuv9HUZWbXC/i6WvjR5iSZkgPvdbnYimtND540iJd4gY2dNkfYxVF6SiKRHIilSrXsCmGs2Nray8G6B8uzB2Q0U8yrf2nU2Mok+vnwR+UvpK3rJqnMOOJ51RtyZRigo8YcSUGGux/Jn5krlNoxyB+/K2tP8lZueuaOd6FEb2hevU=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: pkcs12-keystore-password-dev
      namespace: default

