apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-secret-dev
  namespace: default
  annotations:
    issue-temporary-certificate: "true"
spec:
  secretName: solr-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  commonName: "*.solr-dev.iatistandard.org"
  dnsNames:
    - "solr-dev.iatistandard.org"
    - "*.solr-dev.iatistandard.org"
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        key: password-key
        name: pkcs12-password-secret-dev
  subject:
    countries:
      - UK
    organizationalUnits:
      - k8s
