apiVersion: solr.apache.org/v1beta1
kind: SolrPrometheusExporter
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: prom-exporter-dev
spec:
  customKubeOptions:
    podOptions:
      resources:
        requests:
          cpu: 200m
          memory: 900Mi
  solrReference:
    cloud:
      name: iati-dev
    basicAuthSecret: iati-dev-solrcloud-basic-auth
    solrTLS:
      restartOnTLSSecretUpdate: true
      pkcs12Secret:
        name: solr-tls
        key: keystore.p12
      keyStorePasswordSecret:
        name: pkcs12-password-secret-dev
        key: password-key
  numThreads: 6
