apiVersion: solr.apache.org/v1beta1
kind: SolrPrometheusExporter
metadata:
  name: prom-exporter-prod
spec:
  customKubeOptions:
    podOptions:
      nodeSelector:
        nodepooltype: service
      resources:
        requests:
          cpu: 300m
          memory: 800Mi
  solrReference:
    cloud:
      name: iati-prod
    basicAuthSecret: iati-prod-solrcloud-basic-auth
    solrTLS:
      restartOnTLSSecretUpdate: true
      pkcs12Secret:
        name: solr-tls
        key: keystore.p12
      keyStorePasswordSecret:
        name: pkcs12-password-secret-prod
        key: password-key
  numThreads: 6
