apiVersion: solr.apache.org/v1beta1
kind: SolrCloud
metadata:
  name: iati-dev
spec:
  customSolrKubeOptions:
    ingressOptions:
      ingressClassName: nginx
    podOptions:
      annotations:
        manualrestart: "2021-11-18T15:19:00Z"
      resources:
        limits:
          memory: 8Gi
        requests:
          cpu: 700m
          memory: 8Gi
      initContainers:
        - name: set-zone
          image: roffe/kubectl
          command:
          - '/bin/sh'
          - '-c'
          - |
            zone=$(kubectl get node $NODE_NAME -o jsonpath='{.metadata.labels.topology\.kubernetes\.io/zone}')
            if [ "${zone}" != "" ]; then
                echo "export SOLR_OPTS=\"\${SOLR_OPTS} -Davailability_zone=${zone}\"" > /docker-entrypoint-initdb.d/set-zone.sh
            fi
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          volumeMounts:
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
        - name: "install-extractions-lib"
          image: solr:8.10.1
          command:
          - 'sh'
          - '-c'
          - |
            cp -R /opt/solr-8.10.1/server/solr-webapp/webapp/WEB-INF/lib/* /tmp-webinf-lib
            cp /opt/solr-8.10.1/contrib/extraction/lib/*.jar /tmp-webinf-lib/
            cp /opt/solr-8.10.1/dist/solr-cell-8.10.1.jar /tmp-webinf-lib/
          volumeMounts:
          - mountPath: /tmp-webinf-lib
            name: web-inf-lib
      volumes:
      - defaultContainerMount:
          mountPath: /docker-entrypoint-initdb.d
          name: initdb
        name: initdb
        source:
          emptyDir: {}
      - name: web-inf-lib
        source:
          emptyDir: {}
        defaultContainerMount:
          name: web-inf-lib
          mountPath: /opt/solr-8.10.1/server/solr-webapp/webapp/WEB-INF/lib
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: "technology"
                  operator: In
                  values:
                  - solr-cloud
                - key: "solr-cloud"
                  operator: In
                  values:
                  - iati-dev
              topologyKey: kubernetes.io/hostname
  dataStorage:
    persistent:
      pvcTemplate:
        spec:
          resources:
            requests:
              storage: 128Gi
      reclaimPolicy: Delete
  replicas: 1
  solrImage:
    repository: solr
    tag: 8.10.1
  solrJavaMem: -Xms3g -Xmx3g
  solrOpts: "-Dlog4j2.formatMsgNoLookups=true -Dsolr.cloud.client.stallTime=30000 -Dsolr.environment=dev,label=iati-dev,color=aqua"
  updateStrategy:
    method: Managed
    restartSchedule: "0 6 * * *"
  zookeeperRef:
    provided:
      chroot: /iatisolrdev
      image:
        pullPolicy: IfNotPresent
        repository: pravega/zookeeper
        tag: 0.2.12
      persistence:
        reclaimPolicy: Delete
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
      replicas: 1
      zookeeperPodPolicy:
        annotations:
          manualrestart: "2021-11-22T14:48:00Z"
        resources:
          limits:
            memory: 500Mi
          requests:
            cpu: 250m
            memory: 500Mi
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: "technology"
                    operator: In
                    values:
                    - zookeeper
                  - key: "solr-cloud"
                    operator: In
                    values:
                    - iati-dev
                topologyKey: kubernetes.io/hostname
  solrAddressability:
    commonServicePort: 443
    external:
      domainName: solr-dev.iatistandard.org
      method: Ingress
      nodePortOverride: 443
      useExternalAddress: false
    podPort: 8983
  solrTLS:  
    restartOnTLSSecretUpdate: true
    pkcs12Secret:
      name: solr-tls
      key: keystore.p12
    keyStorePasswordSecret:
      name: pkcs12-keystore-password-dev
      key: password-key
    trustStorePasswordSecret:
      name: lets-encrypt-truststore-secret
      key: password-key
    trustStoreSecret:
      name: lets-encrypt-truststore-secret
      key: truststore.p12
  solrSecurity:
    authenticationType: Basic

